title: "Getting Started with Bioinformatics on Tufts HPC"
description: "Bioinformatics workshop provided by Tufts Research Technology"

plugins:
  - jekyll-relative-links
  - jekyll-toc
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - tutorials/
encoding: UTF-8
