site_name: Getting Started with Bioinformatics on Tufts HPC
site_description: Bioinformatics workshop provided by Tufts Research Technology
theme:
  name: material
  features:
    - content.code.copy
    - navigation.top
    - navigation.sections

nav:
  - Home: index.md
  - Tutorials:
      - Linux Commands: tutorials/linux.md
      - Bioinformatics: tutorials/bioinfo.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true